[package]
name = "turborun"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
crossterm = "0.23"
dialoguer = "0.10.4"

[[bin]]
name = "turborun"
path = "main.rs"
